<a href="https://colab.research.google.com/github/melyneca/Calendar/blob/main/00_pytorch_fund.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
print(torch.__version__)

1.12.0+cu113


In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
vector = torch.tensor([7,6])
vector

tensor([7, 6])

In [ ]:
#MATRIX
Matrix = torch.tensor([[7,2],
                       [3,5]])
Matrix.ndim

2

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
random = torch.rand(3,4)
random

tensor([[0.2444, 0.8695, 0.8444, 0.5059],
        [0.6004, 0.5773, 0.4829, 0.8526],
        [0.4800, 0.1767, 0.9200, 0.9763]])

In [ ]:
zero = torch.zeros(3,4)
one = torch.ones(3,4)

In [ ]:
mult3 = torch.arange(start=0,end=10,step=3)

In [ ]:
# Tensor like
mult4 = torch.zeros_like(input=mult3)
mult4

tensor([0, 0, 0, 0])

In [ ]:
some = torch.rand(3,4)
print(some)
print(f"type: {some.dtype}")
print(f"shape {some.shape}")

tensor([[0.3595, 0.2446, 0.4828, 0.2995],
        [0.8961, 0.0110, 0.2353, 0.9920],
        [0.6746, 0.3815, 0.5316, 0.2954]])
type: torch.float32
shape torch.Size([3, 4])


In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor*tensor

tensor([1, 4, 9])

In [ ]:
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.77 ms, sys: 0 ns, total: 1.77 ms
Wall time: 5.23 ms


In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 75 µs, sys: 0 ns, total: 75 µs
Wall time: 80.3 µs


tensor(14)

In [ ]:
some.type(torch.float32)
torch.mean(some)

tensor(0.4503)